UTC_OFFSET           = "-18000"
TIEMPO_A_REPOSO      = "3.0"
DEBOUNCE_BOTONES     = "0.15"
LONG_PRESS_TIEMPO    = "1.5"
USAR_GAUSSIANA       = "1"
SUAVIZAR_MOVIMIENTOS = "1"
COMPENSACION_ACUMULATIVA = "1"
PRECISION_SUB_PIXEL  = "1"
